# requirements.yml
---
collections:
  # https://github.com/ansible/ansible.platform
  - name: ansible.platform
    src: git+https://github.com/ansible/ansible.platform.git


  # https://github.com/ansible-collections/ansible_hub
  - name: ansible.hub
    src: git+https://github.com/ansible-collections/ansible_hub.git


  # https://github.com/ansible/ansible.controller
  - name: ansible.controller
    src: git+https://github.com/ansible/ansible.controller.git


  # https://github.com/ansible/event-driven-ansible (ansible.eda)
  - name: ansible.eda
    src: git+https://github.com/ansible/event-driven-ansible.git


  # https://github.com/redhat-cop/infra.aap_configuration
  - name: infra.aap_configuration
    src: git+https://github.com/redhat-cop/infra.aap_configuration.git
