---
# Connection details
aap_hostname: https://sandbox-aap-rh-ee-blshaver-dev.apps.rm3.7wse.p1.openshiftapps.com
aap_username: admin
aap_password: mUreuUWzoNrt1WvocX8HAKnwteBBOELf
aap_validate_certs: false  # Set to true in production