---
controller_templates:
- name: job template 1 no roles
  job_type: run 
  inventory: Demo Inventory 
  project: Demo Project 
  playbook: hello_world.yml 

- name: job template 2 with roles
  job_type: run 
  inventory: Demo Inventory 
  project: Demo Project 
  playbook: hello_world.yml 
  roles:
    execute:
      teams:
        - myteam1
        - myteam2